project:
      type: website
      output-dir: docs
    website:
      title: "College Lectures"
      navbar:
        left:
          - href: index.qmd
            text: "All Lectures"
      listing:
        contents: presentations/*.qmd
        type: grid
        sort: "date desc"